### ISSUE TITLE
Increment currrent file overwrites.

### ISSUE THREAD

**Issue by tokejepsen** [Colorbleed/colorbleed-config#125]
**Issue**

When opening a previous version and publish, the current file will increment and overwrite the next version.

**Solution**

Check for existing files and increment to find available file names.

**Comment by BigRoy** [comment]
Does it really? That would be a major bug, haven't seen it happening in production luckily.

Thanks for reporting, this should be investigated and fixed.

**Comment by BigRoy** [comment]
This should actually not be happening when looking at the code in `colorbleed.lib`'s [`version_up` function](https://github.com/Colorbleed/colorbleed-config/blob/master/colorbleed/lib.py#L108) since it [checks the "versioned_up" file exists, and if it does, it increments more](https://github.com/Colorbleed/colorbleed-config/blob/master/colorbleed/lib.py#L147).

@tokejepsen are you sure this issue is still present?

**Comment by BigRoy** [comment]
Tested - and seemed to work correct here. For now I'll assume it's been fixed somewhere along the way.
